// src/app/icon-registration.ts
import { addIcons } from 'ionicons';
import {
  createOutline,
  ribbonOutline,
  informationCircleOutline,
  alertCircle,
  warningOutline,
  homeOutline,
  alertCircleOutline,
  chevronDown,
  searchCircleOutline,
  logOutOutline,
  searchOutline,
  closeCircleOutline,
  checkmarkCircleOutline,
  create,
  arrowBackOutline,
  fileTrayFullOutline,
  closeOutline,
  podiumOutline,
  checkmarkOutline,
  shieldCheckmarkOutline,
  person,
  gitBranchOutline,
  cashOutline,
  personOutline,
  cubeOutline,
  personCircleOutline,
  calendarOutline,
  medalOutline,
  busOutline,
  timeOutline,
  mapOutline,
  settingsOutline,
  pencilOutline,
  carOutline,
  documentTextOutline,
  chatboxOutline,
  // ── Nuevos para excel-import-configurator ─────────────────────────────────
  arrowForwardOutline,
  bulbOutline,
  businessOutline,
  checkmarkCircle,
  closeCircleOutline as closeCircleOutlineIcon,
  cloudUploadOutline,
  documentAttachOutline,
  downloadOutline,
  eyeOutline,
  gitCompareOutline,
  listOutline,
  optionsOutline,
  receiptOutline,
  locationOutline,
  flagOutline,
  sendOutline,
  trashOutline,
  warning,
  folderOpenOutline,
} from 'ionicons/icons';

addIcons({
  // ── Íconos originales ─────────────────────────────────────────────────────
  informationCircleOutline,
  homeOutline,
  alertCircleOutline,
  searchCircleOutline,
  chevronDown,
  chevronDownOutline:  chevronDown,
  searchDownOutline:   searchCircleOutline,
  logOutOutline,
  searchOutline,
  closeCircleOutline,
  checkmarkCircleOutline,
  createOutline,
  ribbonOutline,
  alertCircle,
  warningOutline,
  create,
  podiumOutline,
  checkmarkOutline,
  shieldCheckmarkOutline,
  person,
  gitBranchOutline,
  cashOutline,
  personOutline,
  cubeOutline,
  personCircleOutline,
  calendarOutline,
  medalOutline,
  busOutline,
  timeOutline,
  mapOutline,
  settingsOutline,
  pencilOutline,
  carOutline,
  documentTextOutline,
  chatboxOutline,
  'arrow-back-outline':      arrowBackOutline,
  'file-tray-full-outline':  fileTrayFullOutline,
  'close-outline':           closeOutline,

  // ── Íconos del excel-import-configurator ──────────────────────────────────
  arrowForwardOutline,
  bulbOutline,
  businessOutline,
  'checkmark-circle':        checkmarkCircle,
  cloudUploadOutline,
  documentAttachOutline,
  downloadOutline,
  eyeOutline,
  gitCompareOutline,
  listOutline,
  optionsOutline,
  receiptOutline,
  locationOutline,
  flagOutline,
  sendOutline,
  trashOutline,
  warning,
  folderOpenOutline,
});