// src/app/icon-registration.ts
import { addIcons } from 'ionicons';
import {
  createOutline,
  ribbonOutline,
  informationCircleOutline,
  alertCircle,
  warningOutline,
  homeOutline,
  alertCircleOutline,
  chevronDown,
  searchCircleOutline,
  logOutOutline,
  searchOutline,
  closeCircleOutline,
  checkmarkCircleOutline,
  create,
  arrowBackOutline,
  fileTrayFullOutline,
  closeOutline,
  podiumOutline,checkmarkOutline,
  shieldCheckmarkOutline,
  person,
  gitBranchOutline,
  cashOutline,
  personOutline,
  cubeOutline,
  personCircleOutline,
  calendarOutline,
  medalOutline,
  busOutline,
  timeOutline,
  mapOutline,
  settingsOutline,
  pencilOutline,
  carOutline,
  documentTextOutline,
  chatboxOutline,
} from 'ionicons/icons';

// Registra los iconos que necesitas para tu proyecto
addIcons({
  informationCircleOutline,
  homeOutline,
  alertCircleOutline,
  searchCircleOutline,
  chevronDown,
  chevronDownOutline: chevronDown,
  searchDownOutline: searchCircleOutline,
  logOutOutline,
  searchOutline,
  closeCircleOutline,
  checkmarkCircleOutline,
  createOutline,
  ribbonOutline,
  alertCircle,
  warningOutline,
  create,
  podiumOutline,
  checkmarkOutline,
  shieldCheckmarkOutline,
  person,
  gitBranchOutline,
  cashOutline,
  personOutline,
  cubeOutline,
  personCircleOutline,
  calendarOutline,
  medalOutline,
  busOutline,
  timeOutline,
  mapOutline,
  settingsOutline,
  pencilOutline,
  carOutline,
  documentTextOutline,
  chatboxOutline,
  

  // Iconos agregados por los errores del log
  'arrow-back-outline': arrowBackOutline,
  'file-tray-full-outline': fileTrayFullOutline,
  'close-outline': closeOutline,
});